[ServiceConfiguration]
Name = "seaking"
Port = "8081"
Debug = true

[LoggerConfiguration]
Filename = "./logs/seaking.log"
MaxSize = 100
MaxBackups = 3
MaxAge = 28
Compress = true

[PostgresConfiguration]
Host = "127.0.0.1"
Port = 5432
User = "postgres"
Password = "postgres"
DBName = "mychat"
SSLMode = false
TimeZone = "Asia/Shanghai"

[RedisConfiguration]
Addr = "127.0.0.1:6379"
Password = ""
Db = 0

[JWTConfiguration]
Secret = "your-jwt-secret-key-here"
ExpireHour = 168
